name: CellBase Release workflow

on:
  push:
    tags:
      - '*'
  workflow_dispatch: {}

jobs:
  build:
    uses: opencb/java-common-libs/.github/workflows/build-java-app-workflow.yml@develop
    with:
      maven_opts: -DCELLBASE.WAR.NAME=cellbase

  test:
    uses: ./.github/workflows/test-analysis.yml
    needs: build
    secrets: inherit
#    with:
#      report_context: xetabase
#      report_dir: cellbase

  deploy-maven:
    uses: opencb/java-common-libs/.github/workflows/deploy-maven-repository-workflow.yml@release-4.6.x
    needs: test
    with:
      maven_opts: -Dcheckstyle.skip -DCELLBASE.WAR.NAME=cellbase
    secrets: inherit

  deploy-docker:
    uses: opencb/java-common-libs/.github/workflows/deploy-docker-hub-workflow.yml@release-4.6.x
    needs: test
    with:
      cli: python3 ./build/cloud/docker/docker-build.py push --images base
    secrets: inherit

  deploy-python:
    uses: opencb/java-common-libs/.github/workflows/deploy-python-workflow.yml@release-4.6.x
    needs: test
    with:
      cli: bash ./clients/python/python-build.sh push
      artifact: build-folder
    secrets: inherit

  release:
    uses: opencb/java-common-libs/.github/workflows/release-github-workflow.yml@release-4.6.x
    needs: [deploy-maven, deploy-docker, deploy-python]
