name: CellBase Develop workflow

on:
  push:
    branches:
      - TASK-*
  workflow_dispatch:
    
jobs:
  build:
    uses: opencb/java-common-libs/.github/workflows/build-java-app-workflow.yml@develop

  test:
    uses: ./.github/workflows/test-analysis.yml
    needs: build
    secrets: inherit
    with:
      report_context: development
      report_dir: ${{ github.ref_name }}/cellbase/${{ github.sha }}

  deploy-docker:
    uses: opencb/java-common-libs/.github/workflows/deploy-docker-hub-workflow.yml@develop
    needs: test
    with:
      cli: python3 ./build/cloud/docker/docker-build.py push --images base --tag ${{ github.ref_name }}
    secrets: inherit


