name: CellBase Develop workflow

on:
  push:
    branches:
      - TASK-*
  workflow_dispatch:

env:
  xb_version: "1.5.0"

jobs:
  build:
    uses: opencb/java-common-libs/.github/workflows/build-java-app-workflow.yml@develop
    with:
      maven_opts: -Dcheckstyle.skip -DCELLBASE.WAR.NAME=cellbase

  test:
    name: Test and push Sonar analysis
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Start MongoDB v5.0
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 5.0
          mongodb-replica-set: rs-test
      - name: Test and Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify surefire-report:report org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=opencb_cellbase
      - name: Upload result dir
        uses: actions/upload-artifact@v3
        with:
          name: workdir
          path: |
            ./target
            **/target

  publish-test:
    name: Publish test results
    runs-on: ubuntu-22.04
    needs: test
    strategy:
      matrix:
        module: [ ".","cellbase-core","cellbase-lib","cellbase-client" ]
    steps:
      - name: Download result dir
        uses: actions/download-artifact@v3
        with:
          name: workdir
      - name: Deploy unit tests web recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ${{ matrix.module }}/target/site
          remote: /var/www/html/reports/development/${{ env.xb_version }}/${{ github.ref_name }}/cellbase/${{ github.sha }}/unit/${{ matrix.module }}
          host: ${{ secrets.SSH_TESTING_SERVER_HOST}}
          port: ${{ secrets.SSH_TESTING_SERVER_PORT}}
          username: ${{ secrets.SSH_TESTING_SERVER_USER }}
          password: ${{ secrets.SSH_TESTING_SERVER_PASSWORD }}
          concurrency: 2

  deploy-docker:
    uses: opencb/java-common-libs/.github/workflows/deploy-docker-hub-workflow.yml@develop
    needs: test
    with:
      cli: python3 ./build/cloud/docker/docker-build.py push --images base --tag ${{ github.ref_name }}
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}